# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 18:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(blank=True, upload_to='audio')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2019, 4, 21, 18, 40, 40, 70000, tzinfo=utc), editable=False)),
                ('reponse', models.TextField(null=True)),
                ('confirmation', models.CharField(choices=[('A', 'Absent'), ('P', 'Present')], max_length=1, null=True)),
                ('collaborateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborateur_invitations', related_query_name='collaborateur_invitation', to='Employe.Collaborateur')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('explication', models.TextField()),
                ('ordre', models.IntegerField()),
                ('diarizationResultat', models.TextField(default=True, null=True)),
                ('text', models.TextField(null=True)),
                ('resume', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PV',
            fields=[
                ('reunion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pv', serialize=False, to='Reunion.Reunion')),
                ('file', models.FileField(blank=True, upload_to='pv')),
            ],
        ),
        migrations.AddField(
            model_name='reunion',
            name='dirigeant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employe.Dirigeant'),
        ),
        migrations.AddField(
            model_name='reunion',
            name='rapporteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employe.Rapporteur'),
        ),
        migrations.AddField(
            model_name='point',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='Reunion.Reunion'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', related_query_name='meeting_inviation', to='Reunion.Reunion'),
        ),
        migrations.AddField(
            model_name='enregistrement',
            name='point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enregistrement', to='Reunion.Point'),
        ),
    ]
