# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reunion', '0003_auto_20190424_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 14, 34, 49, 259863, tzinfo=utc), editable=False),
        ),
    ]
