# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-21 18:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collabore', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Collaborators',
            },
        ),
        migrations.CreateModel(
            name='Dirigeant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirige', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Leaders',
            },
        ),
        migrations.CreateModel(
            name='Rapporteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Protractors',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2019, 4, 21, 18, 40, 39, 424000, tzinfo=utc), editable=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False, editable=False)),
                ('sexe', models.CharField(choices=[(b'F', b'Female'), (b'M', b'Male')], max_length=1, null=True)),
                ('poste', models.CharField(max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, upload_to=b'profile_pics')),
                ('phone', models.IntegerField(null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rapporteur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_rapporteur_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dirigeant',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_dirigeant_related', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborateur',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe_collaborateur_related', to=settings.AUTH_USER_MODEL),
        ),
    ]
