# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-23 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 23, 19, 13, 44, 986000, tzinfo=utc), editable=False, null=True),
        ),
    ]
