# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-24 02:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0002_auto_20190423_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 2, 26, 26, 983000, tzinfo=utc), editable=False, null=True),
        ),
    ]
