# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-25 14:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0003_auto_20190424_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 25, 14, 34, 48, 725329, tzinfo=utc), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexe',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
    ]
